# Generated by Django 2.1.4 on 2019-03-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField()),
                ('date', models.DateField()),
                ('balanceInOut', models.BooleanField(default=False)),
                ('amount', models.FloatField()),
                ('remark', models.CharField(max_length=1024)),
            ],
            options={
                'db_table': 'balance',
            },
        ),
    ]
