# Generated by Django 2.1.4 on 2019-03-08 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarFixAccManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('sn', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(max_length=30, null=True)),
                ('price', models.SmallIntegerField(blank=True, null=True)),
                ('usage', models.SmallIntegerField(default=1)),
                ('cost', models.FloatField(default=0)),
                ('guarantee', models.BooleanField(default=False)),
                ('guarantee_price', models.FloatField(default=0, verbose_name='三包价')),
                ('guarantee_time', models.FloatField(default=0, verbose_name='工时')),
                ('guarantee_time_fee', models.FloatField(default=0, verbose_name='工时费')),
                ('old_id', models.IntegerField(blank=True, null=True, verbose_name='old_id')),
            ],
            options={
                'db_table': 'fix_acc',
            },
        ),
        migrations.CreateModel(
            name='CarFixManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.SmallIntegerField(null=True)),
                ('odo', models.IntegerField(null=True)),
                ('date', models.DateField(verbose_name='维修日期')),
                ('reg_time', models.CharField(max_length=24, null=True)),
                ('income', models.SmallIntegerField(default=0, null=True)),
                ('remark', models.CharField(default='', max_length=1024, null=True)),
                ('logging', models.BooleanField(default=False)),
                ('maintain', models.BooleanField(default=False)),
                ('temp_id', models.SmallIntegerField(default=0, null=True)),
                ('old_id', models.IntegerField(null=True, verbose_name='ord_id')),
            ],
            options={
                'db_table': 'car_fix',
            },
        ),
        migrations.CreateModel(
            name='CarInfoManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.SmallIntegerField(null=True)),
                ('sn', models.CharField(max_length=50)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('type', models.CharField(blank=True, max_length=90, null=True)),
                ('buy_date', models.DateField(blank=True, null=True)),
                ('pro_date', models.DateField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=30, null=True)),
                ('remark', models.CharField(blank=True, max_length=100, null=True)),
                ('old_id', models.IntegerField(blank=True, null=True, verbose_name='ord_id')),
            ],
            options={
                'db_table': 'car_info',
            },
        ),
        migrations.CreateModel(
            name='Gurantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, verbose_name='单号')),
                ('apply_date', models.DateTimeField(null=True)),
                ('check_date', models.DateTimeField(null=True)),
                ('repair_type', models.CharField(max_length=10, verbose_name='维修类型')),
                ('gurantee_type', models.CharField(max_length=10, verbose_name='索赔类型')),
                ('check_state', models.CharField(max_length=50, verbose_name='审核状态')),
                ('car_sn', models.CharField(max_length=50, verbose_name='VIN')),
                ('car_type', models.CharField(max_length=50, verbose_name='车型')),
                ('acc_sn', models.CharField(max_length=50, verbose_name='配件代码')),
                ('acc_name', models.CharField(max_length=50, verbose_name='配件名称')),
                ('acc_unit', models.FloatField(default=0, verbose_name='配件单价')),
                ('acc_count', models.FloatField(default=0, verbose_name='配件数')),
                ('acc_fee', models.FloatField(default=0, verbose_name='配件费')),
                ('guarantee_unit', models.FloatField(default=0, verbose_name='工时单价')),
                ('guarantee_time', models.FloatField(default=0, verbose_name='工时数')),
                ('guarantee_time_fee', models.FloatField(default=0, verbose_name='工时费')),
                ('event_fee', models.FloatField(default=0, verbose_name='活动费')),
                ('material_fee', models.FloatField(default=0, verbose_name='辅料费')),
                ('special_fee', models.FloatField(default=0, verbose_name='特殊费')),
                ('total_fee', models.FloatField(default=0, verbose_name='总金额')),
            ],
            options={
                'db_table': 'gurantee',
            },
        ),
        migrations.AddField(
            model_name='carfixmanage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_fix', to='car.CarInfoManage'),
        ),
    ]
