# Generated by Django 2.1.4 on 2019-03-08 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carfixmanage',
            name='fix_man',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.EmployeeManage'),
        ),
        migrations.AddField(
            model_name='carfixaccmanage',
            name='fix',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fix_acc', to='car.CarFixManage'),
        ),
        migrations.AddField(
            model_name='carfixaccmanage',
            name='fix_man',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.EmployeeManage'),
        ),
    ]
