# Generated by Django 2.1.4 on 2019-03-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carfixmanage',
            name='reg_time',
            field=models.CharField(blank=True, max_length=24, null=True),
        ),
    ]
