# Generated by Django 2.1.4 on 2019-03-08 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBonusManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('profit', models.FloatField()),
                ('bonus', models.FloatField(default=0)),
                ('acc_id', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acc_bonus', to='car.CarFixAccManage')),
            ],
            options={
                'db_table': 'bonus',
            },
        ),
        migrations.CreateModel(
            name='EmployeeManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('em_type', models.SmallIntegerField(choices=[(1, '技师'), (2, '文员'), (3, '管理'), (4, '其他')], help_text='类型')),
                ('remark', models.CharField(max_length=48, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.AddField(
            model_name='employeebonusmanage',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.EmployeeManage'),
        ),
        migrations.AddField(
            model_name='employeebonusmanage',
            name='fix_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fix_bonus', to='car.CarFixManage'),
        ),
    ]
