# Generated by Django 2.1.4 on 2019-03-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeManage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24)),
                ('em_type', models.SmallIntegerField(choices=[(1, '技师'), (2, '文员'), (3, '管理'), (4, '其他')], help_text='类型')),
                ('remark', models.CharField(max_length=48, null=True)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
